export const DIRECTION_LEFT = '4'
export const DIRECTION_DOWN = '2'
export const DIRECTION_RIGHT = '6'
export const DIRECTION_UP = '8'
export const DIRECTION_DOWN_LEFT = '1'
export const DIRECTION_DOWN_RIGHT = '3'
export const DIRECTION_UP_LEFT = '7'
export const DIRECTION_UP_RIGHT = '9'
export const DIRECTION_NEUTRAL = '5'

export const BUTTON_A = 'A'
export const BUTTON_B = 'B'
export const BUTTON_C = 'C'
export const BUTTON_X = 'X'
export const BUTTON_Y = 'Y'
export const BUTTON_Z = 'Z'
export const BUTTON_L = 'L'
export const BUTTON_R = 'R'
export const BUTTON_START = 'S'
export const BUTTON_SELECT = 'T' // select/option/back/cancel

export const DIRECTIONS = [
  DIRECTION_LEFT,
  DIRECTION_DOWN,
  DIRECTION_RIGHT,
  DIRECTION_UP
]

export const DIAGONALS = [
  DIRECTION_DOWN_LEFT,
  DIRECTION_DOWN_RIGHT,
  DIRECTION_UP_LEFT,
  DIRECTION_UP_RIGHT
]

export const BUTTONS = [
  BUTTON_X, BUTTON_Y,
  BUTTON_B, BUTTON_A, // H has priority over S
  BUTTON_C, BUTTON_Z,
  BUTTON_L, BUTTON_R,
  BUTTON_START,
  BUTTON_SELECT
]

export const ALL_INPUTS = [
  ...DIRECTIONS,
  ...BUTTONS,
  ...DIAGONALS,
  DIRECTION_NEUTRAL
]

export const REVERSIBLE_DIRECTIONS = [
  DIRECTION_LEFT,
  DIRECTION_DOWN_LEFT,
  DIRECTION_DOWN_RIGHT,
  DIRECTION_RIGHT,
  DIRECTION_UP_RIGHT,
  DIRECTION_UP_LEFT
]

export var OPPOSITES = {}

OPPOSITES[DIRECTION_LEFT] = DIRECTION_RIGHT
OPPOSITES[DIRECTION_DOWN_LEFT] = DIRECTION_DOWN_RIGHT
OPPOSITES[DIRECTION_DOWN_RIGHT] = DIRECTION_DOWN_LEFT
OPPOSITES[DIRECTION_RIGHT] = DIRECTION_LEFT
OPPOSITES[DIRECTION_UP_RIGHT] = DIRECTION_UP_LEFT
OPPOSITES[DIRECTION_UP_LEFT] = DIRECTION_UP_RIGHT
